### ISSUE TITLE
메인 페이지 포스트, 머쓱이 생성 페이지(2)

### ISSUE THREAD

**Issue by from1to2** [prgrms-fe-devcourse/FEDC4_MUSSEUK_LETTER_Donggeun#104]
# ✅ Feature
## Description
머쓱이 카드 25개 설정, 코멘트 개수 순서에 따라 보여주기, 반응형 구현을 주로 진행합니다.

## To-do
메인 페이지
- [x] 통 타입 지정 후의 데이터 25개 가져오기
- [x]  25개 포스트 메시지 개수 순서대로 출력
- [x]  슬라이더 이동 오류 체크
- [x] post 생성 시, 메세지 순서 출력 바로 적용 (뒤로가기 포함)
- [x] PostCard 공통컴포넌트 title, content 내용 초과시, ellipsis등 적용 (...표시)
- [x] 포스트 카드 이미지 조정
- [x]  반응형 구현
- [ ]  포스트 슬라이더 가운데 위치
- [ ]  첫화면 처음 bullet으로 위치 (카드 슬라이더)

머쓱이 생성페이지
- [x]  머쓱이 이미지 두번 클릭 오류 해결
- [x]  전체 UI 크기 조정
- [x]  반응형 구현
- [ ]  머쓱이 생성페이지에서 상세페이지 이동 후, 정상 렌더링 되는지 확인 (최종)

## 기타
따로 팀원과 상의가 필요한 부분들을 적는 공간입니다.

- Galaxy Fold 기기 일때(width값이 아주 작을때 - 280px), 오른쪽 프로필에 공간이 생겨 협의가 필요. ( + 모바일 or 태블릿 버전에서 햄버거 바
![image](https://github.com/prgrms-fe-devcourse/FEDC4_MUSSEUK_LETTER_Donggeun/assets/124763142/e79089e5-507d-4d9c-9692-269b25dc8995)
 이용과 검색창 UI에 대한 협의 필요)
![image](https://github.com/prgrms-fe-devcourse/FEDC4_MUSSEUK_LETTER_Donggeun/assets/124763142/5101de16-f4cd-4cf1-8ba8-38aa1630874d)
