### ISSUE TITLE
useAuthCheckQuery에 개선이 필요해요.

### ISSUE THREAD

**Issue by bbearcookie** [prgrms-fe-devcourse/FEDC4_MUSSEUK_LETTER_Donggeun#110]
# 🚨  Hotfix
## Description
세션 스토리지의 로그인 토큰을 가지고 접속된 사용자의 정보를 관리하는 useAuthCheckQuery 훅에 개선이 필요해요.

## To-do
- [ ] 현재 가공되지 않은 UserResponse 형태의 데이터를 갖고 있어서 우리가 서비스에서 자주 사용하는 User 형태로 변환해야 해요.
- [ ] 예전에 cacheTime을 무한으로 하고 직접 쿼리 데이터를 조작했었는데, 더 좋은 방법을 고민해야겠어요.
- [ ] 네트워크가 불안정할 때 요청에 실패하면 로그인 정보를 다시 가져오려는 시도를 하지 않는 문제가 있어요.

## 기타
따로 팀원과 상의가 필요한 부분들을 적는 공간입니다.
