### ISSUE TITLE
QA 스타일 수정

### ISSUE THREAD

**Issue by from1to2** [prgrms-fe-devcourse/FEDC4_MUSSEUK_LETTER_Donggeun#134]
# ✅ Feature
## Description
QA 스타일 수정

## To-do
메인 페이지
- [x] PostCard 머쓱이 이름 출력 수정
- [x] 카드 사이 여백 pointer 안되게 하기

머쓱 생성페이지
- [x] input 스타일 헤더 로그인에 있는 input 스타일과 통일 (border 색깔)
- [x] textarea minHeight으로 고정. resize: none

## 기타
따로 팀원과 상의가 필요한 부분들을 적는 공간입니다.
