### ISSUE TITLE
메인페이지 슬라이더 수정

### ISSUE THREAD

**Issue by from1to2** [prgrms-fe-devcourse/FEDC4_MUSSEUK_LETTER_Donggeun#136]
# ✅ Feature
## Description
메인페이지 슬라이더 수정

## To-do
메인페이지
- [ ] 슬라이더 첫번째 bullet 설정
- [x] 슬라이더 가운데 정렬

기타
- [x] 머쓱이 이름, 멘트 작성 시 console.log 출력 삭제

## 기타
따로 팀원과 상의가 필요한 부분들을 적는 공간입니다.
