### ISSUE TITLE
슬랙 알림 인증 버그

### ISSUE THREAD

**Issue by juyeon-park** [prgrms-fe-devcourse/FEDC4_MUSSEUK_LETTER_Donggeun#138]
# 🚨  Hotfix
## Description
현재 어떤 어떤 버그가 있는지 작성해주세요. 이미지를 첨부하셔도 좋습니다.

## To-do
- [x] 슬랙 인증 한번 성공했으면 더이상 못하도록 막기
- [x] 슬랙 아이디 제출 시 인증링크가 전송되었습니다 띄우기
- [x] 슬랙 알림 인증시 404 에러 버그 고치기
- [x] 비로그인시 로그인 화면으로 Redirect

## 기타
따로 팀원과 상의가 필요한 부분들을 적는 공간입니다.
