### ISSUE TITLE
header 검색 아이콘 버그 수정 및 스타일 변경

### ISSUE THREAD

**Issue by juyeon-park** [prgrms-fe-devcourse/FEDC4_MUSSEUK_LETTER_Donggeun#140]
# 🚨  Hotfix
## Description
현재 어떤 어떤 버그가 있는지 작성해주세요. 이미지를 첨부하셔도 좋습니다.

## To-do
- [ ] 검색 input width 40rem으로 변경
- [ ] 프로필 이미지 변경하고 다시 접속했을때 헤더의 프로필 이미지 제대로 바뀌는지 확인
- [ ] 검색 아이콘 눌렀을 때 404 에러 버그 고치기

## 기타
따로 팀원과 상의가 필요한 부분들을 적는 공간입니다.
