### ISSUE TITLE
메인페이지, 머쓱이 생성페이지 로딩 작업

### ISSUE THREAD

**Issue by from1to2** [prgrms-fe-devcourse/FEDC4_MUSSEUK_LETTER_Donggeun#153]
# ✅ Feature
## Description
메인페이지, 머쓱이 생성페이지 로딩 작업을 진행합니다.

## To-do
- [x] 메인페이지 NotFound 페이지 처리
- [x] 메인페이지 로딩 처리

- [x] 머쓱이 생성페이지 NotFound 페이지 처리

## 기타
따로 팀원과 상의가 필요한 부분들을 적는 공간입니다.
