### ISSUE TITLE
포스트 페이지 스타일 수정

### ISSUE THREAD

**Issue by Howon-Shin** [prgrms-fe-devcourse/FEDC4_MUSSEUK_LETTER_Donggeun#155]
# ✅ Feature
## Description
포스트 페이지의 스타일을 전체적으로 수정하기

## To-do
- [ ] 장식 크기 증가
- [ ] 텍스트 크기 설정
- [ ] 배경 상위 요소로 분리
- [ ] 머쓱이 크기 정리
- [ ] 텍스트 최대 길이 조정

## 기타
따로 팀원과 상의가 필요한 부분들을 적는 공간입니다.
