### ISSUE TITLE
header 로그인 전/후 조건부 처리 코드 추가

### ISSUE THREAD

**Issue by juyeon-park** [prgrms-fe-devcourse/FEDC4_MUSSEUK_LETTER_Donggeun#16]
# ✅ Feature
## Description
로그인을 안한 상태인 경우, 프로필 알림 아이콘이 안보이고 로그인 버튼이 보이도록 구현하는 기능입니다.

## To-do
- [x] 로그인 조건부 처리 코드 추가
- [x] 로그인 전/후 UI 변경
- [x] header height 64px로 변경 + input height maxwidth 변경

## 기타
따로 팀원과 상의가 필요한 부분들을 적는 공간입니다.
