### ISSUE TITLE
yarn berry + yarn workspace 마이그레이션

### ISSUE THREAD

**Issue by bbearcookie** [prgrms-fe-devcourse/FEDC4_MUSSEUK_LETTER_Donggeun#160]
# ✅ Feature
## Description
yarn berry + yarn workspace 기능을 활용한 패키지 방식으로 마이그레이션 해야 해요.

## To-do
- [x] yarn berry + yarn workspace 설정
- [x] 슬랙 서버 코드 마이그레이션
- [x] 프론트엔드 코드 마이그레이션

## 기타
따로 팀원과 상의가 필요한 부분들을 적는 공간입니다.
