### ISSUE TITLE
메인페이지, 머쓱이생성페이지 마무리 작업

### ISSUE THREAD

**Issue by from1to2** [prgrms-fe-devcourse/FEDC4_MUSSEUK_LETTER_Donggeun#178]
# ✅ Feature
## Description
메인페이지, 머쓱이생성페이지 마무리 작업

## To-do

메인페이지

- [x] table 삭제, galaxy fold 반응형 이미지 위치 수정
- [x]  map함수 모든 Post로 적용 (DB 리셋)

머쓱이생성페이지

- [x]  로딩 추가
- [x]  모든 input 글자 수 제한
- [x] 글자수 제한 문구 추가

## 기타
따로 팀원과 상의가 필요한 부분들을 적는 공간입니다.
