### ISSUE TITLE
라우팅 관련 리팩토링

### ISSUE THREAD

**Issue by bbearcookie** [prgrms-fe-devcourse/FEDC4_MUSSEUK_LETTER_Donggeun#202]
# 🛠️ Refactor
## Description
현재 `routes/index.tsx` 는 사용되지 않고 있는 형태이기에 삭제 작업이 필요해요!
추가적으로 리팩토링 하거나 고려해볼 사항을 적어봤어요!

## To-do
- [ ] 기존의 `routes/index.tsx` 제거
- [ ] 라우팅 관련 설정을 `App.tsx` 가 아니라, 다른 라우팅 파일을 만들어서 처리하는 것 고려해보기
- [ ] react-router-dom v6 에 등장한 createBrowserRouter 를 사용하는 방법 고려해보기

## 기타
