### ISSUE TITLE
메인페이지 '최신순' 슬라이더 추가

### ISSUE THREAD

**Issue by from1to2** [prgrms-fe-devcourse/FEDC4_MUSSEUK_LETTER_Donggeun#207]
# ✅ Feature
## Description
머쓱이 '최신순' 슬라이더 추가. 기타 필요 작업 수행.

## To-do
- [ ] Post 공통 타입에 createdAt, updatedAt을 추가
- [ ] util 함수 parsePost의 createdAt, updatedAt -> return값으로 추가
- [ ] 메인페이지 swiper slider를 컴포넌트화

- [ ] 머쓱이 '최신순' 슬라이더 추가

## 기타
따로 팀원과 상의가 필요한 부분들을 적는 공간입니다.
