### ISSUE TITLE
메인페이지 기능구현

### ISSUE THREAD

**Issue by from1to2** [prgrms-fe-devcourse/FEDC4_MUSSEUK_LETTER_Donggeun#31]
# ✅ Feature
## Description
메인페이지 기능구현.

## To-do
- [x] 나만의 머쓱이 만들기 버튼을 누르면 머쓱이 추가 페이지로 이동한다
- [x] newpost 페이지 뒤로가기 페이지 이동 (추가구현)
<br>

- [x] 메인 페이지 하단에 머쓱이 카드 목록(카드 5개)를 볼 수 있다

## 기타
따로 팀원과 상의가 필요한 부분들을 적는 공간입니다.
