### ISSUE TITLE
폰트 경로 수정, 회원가입 스타일 수정

### ISSUE THREAD

**Issue by bbearcookie** [prgrms-fe-devcourse/FEDC4_MUSSEUK_LETTER_Donggeun#32]
# 🚨  Hotfix

## To-do
- [x] 폰트 경로에 alias 대신 절대경로를 사용하도록 바꿔야 해요.
- [x] 회원가입에서 InputField를 구현할 때 차크라 UI에서 제공하는 FormControl을 사용하도록 수정해야 해요.
- [x] 색상 테마 지정 방식의 변화에 대한 부분을 대응해야 해요.

## 기타
따로 팀원과 상의가 필요한 부분들을 적는 공간입니다.
