### ISSUE TITLE
URL path에 따라서 빈 페이지를 렌더링하도록 기본적인 라우팅을 세팅해야 해요.

### ISSUE THREAD

**Issue by bbearcookie** [prgrms-fe-devcourse/FEDC4_MUSSEUK_LETTER_Donggeun#5]
# ✅ Feature
## Description
[기획서](https://prgrms.notion.site/4452564c86ae419ca0f3b06a68cd8c4e)의 폴더 구조를 참고하여 메인 페이지, 사용자 상세 페이지, ... 등등 각각의 페이지에 해당하는 `index.tsx` 파일을 만들고 URL path에 따라서 연결되도록 react-router 초기 세팅을 해야 해요!

## To-do
- [x] `/routes/index.ts` 작성
- [x] 페이지별 `/pages/*/index.tsx` 작성
- [x] 각각의 빈 페이지를 보여주도록 라우팅 연결

## 기타
[react-router-dom v6](https://reactrouter.com/en/main/start/overview) 버전에서 몇 가지 변경된 내용이 존재하는 것으로 알고 있는데 해당 방법을 찾아서 적용하면 좋을 것 같아요!
