### ISSUE TITLE
메인페이지, 머쓱이 생성 페이지 디자인 수정

### ISSUE THREAD

**Issue by from1to2** [prgrms-fe-devcourse/FEDC4_MUSSEUK_LETTER_Donggeun#58]
# ✅ Feature
## Description
메인, 머쓱이 페이지 디자인 수정

## To-do
메인페이지
- [x] 페이지네이션 스타일 변경
- [x] 카드 위치 변경
- [x] 불필요 여백 제거

머쓱이 생성페이지
- [x] 불필요 여백 제거
- [x] 선택아이콘 바 생성
- [x] 아이콘 선택
- [x] 기타 스타일 수정

기타
- [x] 메인페이지 불필요 폴더 제거

## 기타
따로 팀원과 상의가 필요한 부분들을 적는 공간입니다.
