### ISSUE TITLE
API 처리 관련 사전 작업

### ISSUE THREAD

**Issue by bbearcookie** [prgrms-fe-devcourse/FEDC4_MUSSEUK_LETTER_Donggeun#6]
# ✅ Feature
## Description
API 요청에 필요한 사전 작업을 해야해요.
이 이슈와 관련된 태스크가 긴밀하게 엮여있으면서도 분량이 많은 것 같기는 해서 나중에 세부 분할이 가능하다면 나눠도 좋을 것 같아요! 우선 작성 해 놓을게요! 😁

## To-do
- [ ] postman 등 도구의 도움으로 실제 API 요청을 테스트해보고 원하는 응답을 받을 수 있는지 알아보기
- [ ] 우리 서비스에서 사용할 API 요청을 수행하는 쿼리 함수 작성하기 및 응답 데이터 타입 정의
- [ ] useQuery 커스텀 훅 작성 및 쿼리 키 정리
- [ ] useMutation 커스텀 훅 작성

## 작업 결과
처음에는 간단한 타입 정리 작업이라고 생각했었는데, 생각보다 API 호출에 대한 부분을 정리하면서 구현에 대한 부분이 많이 들어갈 것 같습니다..
우선 공통적으로 사용할 수 있는 axios 인스턴스만 정리해놓고, 예시 커스텀 훅의 느낌으로 로그인 관련 훅만 작성 해 놓았는데..  더 다양한 API에 대한 부분은 구현하면서 논의가 필요할 것 같습니다.
