### ISSUE TITLE
편지 한눈에 보기 모달 구현

### ISSUE THREAD

**Issue by juyeon-park** [prgrms-fe-devcourse/FEDC4_MUSSEUK_LETTER_Donggeun#76]
# ✅ Feature
## Description
리스트로 보기 버튼을 클릭하면 받은 편지의 내용들이 아코디언 형식으로 한눈에 보이는 모달을 구현하는 것입니다.

## To-do
- [ ] 아코디언 UI 구현 - chakra accodion ui 사용
- [ ] 실제 api 데이터 연결
- [ ] 리스트로 보기 버튼 클릭시 modal open

## 기타
따로 팀원과 상의가 필요한 부분들을 적는 공간입니다.
