### ISSUE TITLE
메인페이지, 머쓱이 추가페이지 UI 구현

### ISSUE THREAD

**Issue by from1to2** [prgrms-fe-devcourse/FEDC4_MUSSEUK_LETTER_Donggeun#9]
# ✅ Feature
## Description
메인페이지 UI를 구현합니다.
머쓱이페이지 UI를 구현합니다.
## To-do
- [x] 메인페이지 UI 구현
- [x] 머쓱이페이지 UI 구현
- [x] 메인페이지 슬라이더 구현
- [x] 메인페이지 세부  UI 구현
- [x] 머쓱이페이지 세부  UI 구현
- [x] 상의 후 기타 스타일 구현 마무리
## 기타
따로 팀원과 상의가 필요한 부분들을 적는 공간입니다.
